#!/bin/bash
#
# Test Suite for: linear-create project dependencies (M23)
#
# This script tests all dependency management commands:
#   - project create/update with dependency flags
#   - project dependencies add/remove/list/clear
#   - project view (dependency display)
#   - project list --show-dependencies
#
# Setup Requirements:
#   - LINEAR_API_KEY environment variable must be set
#   - linear-create must be built (npm run build)
#   - You should have at least one team in your Linear workspace
#
# Usage:
#   ./test-project-dependencies.sh [OPTIONS]
#
# Options:
#   --test N        Run only test #N
#   --start N       Run tests starting from #N
#   --end N         Run tests up to #N
#   --range N-M     Run tests from #N to #M
#   --verbose, -v   Show full command output
#   --help, -h      Show help message
#
# Examples:
#   ./test-project-dependencies.sh                # Run all tests
#   ./test-project-dependencies.sh --test 5       # Run only test #5
#   ./test-project-dependencies.sh --range 1-10   # Run tests 1-10
#
# Output:
#   - Creates TEST_DEP_* prefixed projects in Linear
#   - Generates cleanup-dependencies-test.sh for cleanup
#   - Prints summary of passed/failed/skipped tests
#

set -e  # Exit on first error
set -o pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PASSED=0
FAILED=0
SKIPPED=0
TEST_COUNT=0
CLI_CMD="node dist/index.js"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
TEST_PREFIX="TEST_DEP_${TIMESTAMP}"

# Test range configuration
START_TEST=1
END_TEST=999999
VERBOSE=false

# Cleanup script
CLEANUP_SCRIPT="cleanup-dependencies-test.sh"

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --test)
            START_TEST="$2"
            END_TEST="$2"
            shift 2
            ;;
        --start)
            START_TEST="$2"
            shift 2
            ;;
        --end)
            END_TEST="$2"
            shift 2
            ;;
        --range)
            IFS='-' read -r START_TEST END_TEST <<< "$2"
            shift 2
            ;;
        --verbose|-v)
            VERBOSE=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --test N        Run only test #N"
            echo "  --start N       Run tests starting from #N"
            echo "  --end N         Run tests up to #N"
            echo "  --range N-M     Run tests from #N to #M"
            echo "  --verbose, -v   Show full output"
            echo "  --help, -h      Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

echo "=================================================="
echo "  PROJECT DEPENDENCIES (M23) - TEST SUITE"
echo "=================================================="
echo "CLI command: $CLI_CMD"
echo "Test prefix: $TEST_PREFIX"
if [ "$START_TEST" -ne 1 ] || [ "$END_TEST" -ne 999999 ]; then
    echo "Test range: #$START_TEST to #$END_TEST"
fi
echo ""

# Check prerequisites
if [ -z "$LINEAR_API_KEY" ]; then
    echo -e "${RED}ERROR: LINEAR_API_KEY environment variable not set${NC}"
    exit 1
fi

if [ ! -f "dist/index.js" ]; then
    echo -e "${RED}ERROR: dist/index.js not found. Run 'npm run build' first${NC}"
    exit 1
fi

# Get test team
echo "Fetching test data from Linear..."
TEAMS_JSON=$($CLI_CMD teams list --format json 2>/dev/null || echo "[]")
TEST_TEAM_ID=$(echo "$TEAMS_JSON" | node -e "const data=require('fs').readFileSync(0,'utf-8'); const teams=JSON.parse(data); console.log(teams[0]?.id || '')")

if [ -z "$TEST_TEAM_ID" ]; then
    echo -e "${RED}ERROR: No teams found in workspace${NC}"
    exit 1
fi

TEST_TEAM_NAME=$(echo "$TEAMS_JSON" | node -e "const data=require('fs').readFileSync(0,'utf-8'); const teams=JSON.parse(data); console.log(teams[0]?.name || '')")
echo "Using test team: $TEST_TEAM_NAME ($TEST_TEAM_ID)"
echo ""

# Initialize cleanup script
cat > "$CLEANUP_SCRIPT" << EOF
#!/bin/bash
# Generated by test-project-dependencies.sh on $(date)
# This script lists test projects created during dependency testing.
# Review and manually delete them via Linear UI.

echo "Test projects created by test-project-dependencies.sh:"
echo "Prefix: ${TEST_PREFIX}"
echo ""
echo "Projects to clean up:"
EOF
chmod +x "$CLEANUP_SCRIPT"

# ============================================================
# HELPER FUNCTIONS
# ============================================================

run_test() {
    local description="$1"
    local command="$2"
    local should_fail="${3:-false}"

    ((TEST_COUNT++))

    # Check if test should be skipped based on range
    if [ "$TEST_COUNT" -lt "$START_TEST" ] || [ "$TEST_COUNT" -gt "$END_TEST" ]; then
        echo "=================================================="
        echo -e "${YELLOW}TEST #${TEST_COUNT}: ${description}${NC}"
        echo -e "${YELLOW}⊘ SKIPPED (outside test range)${NC}"
        echo ""
        ((SKIPPED++))
        return 0
    fi

    echo "=================================================="
    echo -e "${BLUE}TEST #${TEST_COUNT}: ${description}${NC}"
    echo "COMMAND: $command"
    echo "--------------------------------------------------"

    if [ "$should_fail" = "true" ]; then
        # This test should fail
        if eval "$command" > /dev/null 2>&1; then
            echo -e "${RED}❌ FAILED (expected to fail but succeeded)${NC}"
            ((FAILED++))
        else
            echo -e "${GREEN}✅ PASSED (failed as expected)${NC}"
            ((PASSED++))
        fi
    else
        # This test should succeed
        if [ "$VERBOSE" = "true" ]; then
            if eval "$command"; then
                echo -e "${GREEN}✅ PASSED${NC}"
                ((PASSED++))
            else
                echo -e "${RED}❌ FAILED${NC}"
                ((FAILED++))
            fi
        else
            # Truncate output in non-verbose mode
            OUTPUT=$(eval "$command" 2>&1 || echo "COMMAND_FAILED")
            if [[ "$OUTPUT" == *"COMMAND_FAILED"* ]]; then
                echo -e "${RED}❌ FAILED${NC}"
                echo "$OUTPUT" | head -20
                ((FAILED++))
            else
                echo "$OUTPUT" | head -10
                echo -e "${GREEN}✅ PASSED${NC}"
                ((PASSED++))
            fi
        fi
    fi

    echo ""
}

# ============================================================
# PHASE 1: Create Test Projects
# ============================================================

echo "=================================================="
echo "PHASE 1: Creating test projects for dependency testing"
echo "=================================================="
echo ""

# Create ProjectA, ProjectB, ProjectC (base projects)
echo "Creating ProjectA..."
PROJECT_A_ID=$($CLI_CMD project create --title "${TEST_PREFIX}_ProjectA" --team "$TEST_TEAM_ID" --format json 2>/dev/null | node -e "const data=require('fs').readFileSync(0,'utf-8'); const proj=JSON.parse(data); console.log(proj.id)")
echo "  ProjectA ID: $PROJECT_A_ID"
echo "echo '  ${TEST_PREFIX}_ProjectA ($PROJECT_A_ID)'" >> "$CLEANUP_SCRIPT"

echo "Creating ProjectB..."
PROJECT_B_ID=$($CLI_CMD project create --title "${TEST_PREFIX}_ProjectB" --team "$TEST_TEAM_ID" --format json 2>/dev/null | node -e "const data=require('fs').readFileSync(0,'utf-8'); const proj=JSON.parse(data); console.log(proj.id)")
echo "  ProjectB ID: $PROJECT_B_ID"
echo "echo '  ${TEST_PREFIX}_ProjectB ($PROJECT_B_ID)'" >> "$CLEANUP_SCRIPT"

echo "Creating ProjectC..."
PROJECT_C_ID=$($CLI_CMD project create --title "${TEST_PREFIX}_ProjectC" --team "$TEST_TEAM_ID" --format json 2>/dev/null | node -e "const data=require('fs').readFileSync(0,'utf-8'); const proj=JSON.parse(data); console.log(proj.id)")
echo "  ProjectC ID: $PROJECT_C_ID"
echo "echo '  ${TEST_PREFIX}_ProjectC ($PROJECT_C_ID)'" >> "$CLEANUP_SCRIPT"

echo ""
echo "Test projects created successfully!"
echo ""

# ============================================================
# PHASE 2: Test project create with dependencies
# ============================================================

run_test \
  "Create project with --depends-on (simple mode)" \
  "$CLI_CMD project create --title '${TEST_PREFIX}_Create1' --team '$TEST_TEAM_ID' --depends-on '$PROJECT_A_ID'"

run_test \
  "Create project with --blocks (simple mode)" \
  "$CLI_CMD project create --title '${TEST_PREFIX}_Create2' --team '$TEST_TEAM_ID' --blocks '$PROJECT_B_ID'"

run_test \
  "Create project with both --depends-on and --blocks" \
  "$CLI_CMD project create --title '${TEST_PREFIX}_Create3' --team '$TEST_TEAM_ID' --depends-on '$PROJECT_A_ID' --blocks '$PROJECT_B_ID'"

run_test \
  "Create project with --dependency (advanced mode)" \
  "$CLI_CMD project create --title '${TEST_PREFIX}_Create4' --team '$TEST_TEAM_ID' --dependency '$PROJECT_A_ID:end:start'"

run_test \
  "Create project with multiple dependencies (comma-separated)" \
  "$CLI_CMD project create --title '${TEST_PREFIX}_Create5' --team '$TEST_TEAM_ID' --depends-on '$PROJECT_A_ID,$PROJECT_B_ID'"

run_test \
  "Create project with mixed simple and advanced syntax" \
  "$CLI_CMD project create --title '${TEST_PREFIX}_Create6' --team '$TEST_TEAM_ID' --depends-on '$PROJECT_A_ID' --dependency '$PROJECT_C_ID:start:end'"

# ============================================================
# PHASE 3: Test project dependencies add command
# ============================================================

run_test \
  "Add depends-on dependency to ProjectA" \
  "$CLI_CMD project dependencies add '$PROJECT_A_ID' --depends-on '$PROJECT_B_ID'"

run_test \
  "Add blocks dependency to ProjectA" \
  "$CLI_CMD project dependencies add '$PROJECT_A_ID' --blocks '$PROJECT_C_ID'"

run_test \
  "Add advanced dependency to ProjectB" \
  "$CLI_CMD project dependencies add '$PROJECT_B_ID' --dependency '$PROJECT_C_ID:start:start'"

run_test \
  "Add multiple dependencies (comma-separated)" \
  "$CLI_CMD project dependencies add '$PROJECT_C_ID' --depends-on '$PROJECT_A_ID,$PROJECT_B_ID'"

run_test \
  "Add duplicate dependency (should skip gracefully)" \
  "$CLI_CMD project dependencies add '$PROJECT_A_ID' --depends-on '$PROJECT_B_ID'"

run_test \
  "Add self-referential dependency (should skip with warning)" \
  "$CLI_CMD project dependencies add '$PROJECT_A_ID' --depends-on '$PROJECT_A_ID'" \
  false

# ============================================================
# PHASE 4: Test project dependencies list command
# ============================================================

run_test \
  "List all dependencies for ProjectA" \
  "$CLI_CMD project dependencies list '$PROJECT_A_ID'"

run_test \
  "List only depends-on dependencies" \
  "$CLI_CMD project dependencies list '$PROJECT_A_ID' --direction depends-on"

run_test \
  "List only blocks dependencies" \
  "$CLI_CMD project dependencies list '$PROJECT_A_ID' --direction blocks"

run_test \
  "List dependencies using deps alias" \
  "$CLI_CMD proj deps ls '$PROJECT_B_ID'"

# ============================================================
# PHASE 5: Test project view with dependencies
# ============================================================

run_test \
  "View project with dependencies displayed" \
  "$CLI_CMD project view '$PROJECT_A_ID'"

# ============================================================
# PHASE 6: Test project list with --show-dependencies
# ============================================================

run_test \
  "List projects with dependency counts" \
  "$CLI_CMD project list --team '$TEST_TEAM_ID' --show-dependencies --limit 5"

run_test \
  "List projects without dependency counts (default)" \
  "$CLI_CMD project list --team '$TEST_TEAM_ID' --limit 5"

# ============================================================
# PHASE 7: Test project update with dependencies
# ============================================================

run_test \
  "Update project to add dependency via update command" \
  "$CLI_CMD project update '$PROJECT_A_ID' --depends-on '$PROJECT_C_ID'"

run_test \
  "Update project to remove dependency via update command" \
  "$CLI_CMD project update '$PROJECT_A_ID' --remove-depends-on '$PROJECT_B_ID'"

# ============================================================
# PHASE 8: Test project dependencies remove command
# ============================================================

run_test \
  "Remove depends-on dependency by direction" \
  "$CLI_CMD project dependencies remove '$PROJECT_C_ID' --depends-on '$PROJECT_A_ID'"

run_test \
  "Remove blocks dependency by direction" \
  "$CLI_CMD project dependencies remove '$PROJECT_A_ID' --blocks '$PROJECT_C_ID'"

run_test \
  "Remove all dependencies with specific project" \
  "$CLI_CMD project dependencies remove '$PROJECT_B_ID' --with '$PROJECT_C_ID'"

# Get a relation ID for testing
RELATION_ID=$($CLI_CMD project dependencies list "$PROJECT_A_ID" 2>/dev/null | grep -oE '\[([a-f0-9-]+)\]' | head -1 | tr -d '[]' || echo "")

if [ -n "$RELATION_ID" ]; then
    run_test \
      "Remove dependency by relation ID" \
      "$CLI_CMD project dependencies remove '$PROJECT_A_ID' --relation-id '$RELATION_ID'"
else
    echo "⚠️  Skipping relation ID test (no relations found)"
    ((SKIPPED++))
fi

# ============================================================
# PHASE 9: Test project dependencies clear command
# ============================================================

run_test \
  "Clear all dependencies with --yes flag" \
  "$CLI_CMD project dependencies clear '$PROJECT_A_ID' --yes"

run_test \
  "Clear only depends-on dependencies" \
  "$CLI_CMD project dependencies clear '$PROJECT_C_ID' --direction depends-on --yes"

run_test \
  "Clear only blocks dependencies" \
  "$CLI_CMD project dependencies clear '$PROJECT_B_ID' --direction blocks --yes"

# ============================================================
# PHASE 10: Test error cases and validation
# ============================================================

run_test \
  "Add dependency without flags (should fail)" \
  "$CLI_CMD project dependencies add '$PROJECT_A_ID'" \
  true

run_test \
  "Remove dependency without flags (should fail)" \
  "$CLI_CMD project dependencies remove '$PROJECT_A_ID'" \
  true

run_test \
  "Add dependency with invalid anchor type (should fail)" \
  "$CLI_CMD project dependencies add '$PROJECT_A_ID' --dependency '$PROJECT_B_ID:invalid:start'" \
  true

run_test \
  "Add dependency with malformed syntax (should fail)" \
  "$CLI_CMD project dependencies add '$PROJECT_A_ID' --dependency '$PROJECT_B_ID:start'" \
  true

run_test \
  "List dependencies for non-existent project (should fail)" \
  "$CLI_CMD project dependencies list 'nonexistent-project-id'" \
  true

# ============================================================
# SUMMARY
# ============================================================

echo ""
echo "cat >> '$CLEANUP_SCRIPT' << 'FOOTER'" >> "$CLEANUP_SCRIPT"
cat >> "$CLEANUP_SCRIPT" << 'FOOTER'

echo ""
echo "To delete these projects, use the Linear UI or wait for delete command implementation."
echo "Total test projects created: 9+ projects"
FOOTER

echo "=================================================="
echo "  TEST SUITE SUMMARY"
echo "=================================================="
echo -e "Total tests:    ${TEST_COUNT}"
echo -e "Passed:         ${GREEN}${PASSED}${NC}"
echo -e "Failed:         ${RED}${FAILED}${NC}"
echo -e "Skipped:        ${YELLOW}${SKIPPED}${NC}"
echo ""

if [ "$FAILED" -gt 0 ]; then
    echo -e "${RED}❌ Some tests failed${NC}"
    echo "Cleanup script generated: $CLEANUP_SCRIPT"
    exit 1
else
    echo -e "${GREEN}✅ All tests passed!${NC}"
    echo "Cleanup script generated: $CLEANUP_SCRIPT"
    exit 0
fi
